# Keys are language codes according to the standard ISO 639-1.
# Values are what the languages are called in English.
#
# (Some of these are "macrolanguages" consisting of several related
# languagues.)

langnames = {'ab': 'Abkhazian',
             'aa': 'Afar',
             'af': 'Afrikaans',
             'ak': 'Akan',
             'sq': 'Albanian',
             'am': 'Amharic',
             'ar': 'Arabic',
             'an': 'Aragonese',
             'hy': 'Armenian',
             'as': 'Assamese',
             'av': 'Avaric',
             'ae': 'Avestan',
             'ay': 'Aymara',
             'az': 'Azerbaijani',
             'bm': 'Bambara',
             'ba': 'Bashkir',
             'eu': 'Basque',
             'be': 'Belarusian',
             'bn': 'Bengali',
             'bh': 'Bihari languages',
             'bi': 'Bislama',
             'bs': 'Bosnian',
             'br': 'Breton',
             'bg': 'Bulgarian',
             'my': 'Burmese',
             'ca': 'Catalan',
             'ch': 'Chamorro',
             'ce': 'Chechen',
             'ny': 'Chichewa',
             'zh': 'Chinese',
             'cv': 'Chuvash',
             'kw': 'Cornish',
             'co': 'Corsican',
             'cr': 'Cree',
             'hr': 'Croatian',
             'cs': 'Czech',
             'da': 'Danish',
             'dv': 'Divehi',
             'nl': 'Dutch',
             'dz': 'Dzongkha',
             'en': 'English',
             'eo': 'Esperanto',
             'et': 'Estonian',
             'ee': 'Ewe',
             'fo': 'Faroese',
             'fj': 'Fijian',
             'fi': 'Finnish',
             'fr': 'French',
             'ff': 'Fulah',
             'gl': 'Galician',
             'ka': 'Georgian',
             'de': 'German',
             'el': 'Greek',
             'gn': 'Guarani',
             'gu': 'Gujarati',
             'ht': 'Haitian',
             'ha': 'Hausa',
             'he': 'Hebrew',
             'hz': 'Herero',
             'hi': 'Hindi',
             'ho': 'Hiri Motu',
             'hu': 'Hungarian',
             'ia': 'Interlingua',
             'id': 'Indonesian',
             'ie': 'Interlingue',
             'ga': 'Irish',
             'ig': 'Igbo',
             'ik': 'Inupiaq',
             'io': 'Ido',
             'is': 'Icelandic',
             'it': 'Italian',
             'iu': 'Inuktitut',
             'ja': 'Japanese',
             'jv': 'Javanese',
             'kl': 'Kalaallisut',
             'kn': 'Kannada',
             'kr': 'Kanuri',
             'ks': 'Kashmiri',
             'kk': 'Kazakh',
             'km': 'Central Khmer',
             'ki': 'Kikuyu',
             'rw': 'Kinyarwanda',
             'ky': 'Kirghiz',
             'kv': 'Komi',
             'kg': 'Kongo',
             'ko': 'Korean',
             'ku': 'Kurdish',
             'kj': 'Kuanyama',
             'la': 'Latin',
             'lb': 'Luxembourgish',
             'lg': 'Ganda',
             'li': 'Limburgan',
             'ln': 'Lingala',
             'lo': 'Lao',
             'lt': 'Lithuanian',
             'lu': 'Luba-Katanga',
             'lv': 'Latvian',
             'gv': 'Manx',
             'mk': 'Macedonian',
             'mg': 'Malagasy',
             'ms': 'Malay',
             'ml': 'Malayalam',
             'mt': 'Maltese',
             'mi': 'Maori',
             'mr': 'Marathi',
             'mh': 'Marshallese',
             'mn': 'Mongolian',
             'na': 'Nauru',
             'nv': 'Navajo',
             'nd': 'North Ndebele',
             'ne': 'Nepali',
             'ng': 'Ndonga',
             'nb': 'Norwegian Bokmål',
             'nn': 'Norwegian Nynorsk',
             'no': 'Norwegian',
             'ii': 'Sichuan Yi',
             'nr': 'South Ndebele',
             'oc': 'Occitan',
             'oj': 'Ojibwa',
             'cu': 'Church Slavic',
             'om': 'Oromo',
             'or': 'Oriya',
             'os': 'Ossetian',
             'pa': 'Punjabi',
             'pi': 'Pali',
             'fa': 'Persian',
             'pl': 'Polish',
             'ps': 'Pashto',
             'pt': 'Portuguese',
             'qu': 'Quechua',
             'rm': 'Romansh',
             'rn': 'Rundi',
             'ro': 'Romanian',
             'ru': 'Russian',
             'sa': 'Sanskrit',
             'sc': 'Sardinian',
             'sd': 'Sindhi',
             'se': 'Northern Sami',
             'sm': 'Samoan',
             'sg': 'Sango',
             'sr': 'Serbian',
             'gd': 'Gaelic',
             'sn': 'Shona',
             'si': 'Sinhala',
             'sk': 'Slovak',
             'sl': 'Slovenian',
             'so': 'Somali',
             'st': 'Southern Sotho',
             'es': 'Spanish',
             'su': 'Sundanese',
             'sw': 'Swahili',
             'ss': 'Swati',
             'sv': 'Swedish',
             'ta': 'Tamil',
             'te': 'Telugu',
             'tg': 'Tajik',
             'th': 'Thai',
             'ti': 'Tigrinya',
             'bo': 'Tibetan',
             'tk': 'Turkmen',
             'tl': 'Tagalog',
             'tn': 'Tswana',
             'to': 'Tonga',
             'tr': 'Turkish',
             'ts': 'Tsonga',
             'tt': 'Tatar',
             'tw': 'Twi',
             'ty': 'Tahitian',
             'ug': 'Uighur',
             'uk': 'Ukrainian',
             'ur': 'Urdu',
             'uz': 'Uzbek',
             've': 'Venda',
             'vi': 'Vietnamese',
             'vo': 'Volapük',
             'wa': 'Walloon',
             'cy': 'Welsh',
             'wo': 'Wolof',
             'fy': 'Western Frisian',
             'xh': 'Xhosa',
             'yi': 'Yiddish',
             'yo': 'Yoruba',
             'za': 'Zhuang',
             'zu': 'Zulu',
             }


def can_speak(langcodes):
    language_name = []
    for lc in langcodes:
        if lc in langnames.keys():
            language_name.append((langnames.get(lc, 'an unidentified language')))
            language_name.sort()
    if len(language_name) == 0:
        return 'I cannot speak'
    elif len(language_name) == 1:
        return f'I can only speak {language_name[0]}'
    elif len(language_name) == 2:
        return f'I can speak {language_name[0]} and {language_name[1]}'
    else:
        return f'I can speak {", ".join(language_name[:- 2])}, {language_name[-2]} and {language_name[-1]}.'


def guess_code(language):
    for ln in langnames:
        if langnames[ln] == language:
            return language[:2].lower()


def report_no_match():
    for code in sorted(langnames):
        if code != guess_code(langnames[code]).lower():
            print(f'{code} does not match {langnames[code]}')


def report_traps():
    for langname in langnames.values():
        if guess_code(langname) in langnames.keys():
            if langnames[guess_code(langname)] != langname:
                print(f'{langname} is not "{guess_code(langname)}". That means {langnames.get(guess_code(langname))}.')

